# Generated by Django 2.2.15 on 2020-11-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201125_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='lcno',
            field=models.CharField(max_length=30, verbose_name='lcno'),
        ),
    ]
