# Generated by Django 2.2.15 on 2020-11-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20201125_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='lcno',
            field=models.CharField(max_length=30, verbose_name='lcno'),
        ),
    ]
