# Generated by Django 2.2.15 on 2020-12-16 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201108_2243'),
        ('account', '0009_auto_20201126_0045'),
    ]

    operations = [
    ]
